Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "forwarded_port", guest: 80, host: 8089
  
  #_Configuração de rede privada com IP estatico
  # config.vm.network "private_network", ip: "192.168.56.4"

  #_Configuração de rede privada com dhcp
  #  config.vm.network "private_network", type: "dhcp"

  config.vm.network "public_network", type: "dhcp"
end